// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdII7GbFYsN9Q0BXiZtfU039gcmHNTRes',
    appId: '1:448392600157:web:8cd8278399662e24dccbb4',
    messagingSenderId: '448392600157',
    projectId: 'testing-cli-a28a7',
    authDomain: 'testing-cli-a28a7.firebaseapp.com',
    storageBucket: 'testing-cli-a28a7.appspot.com',
    measurementId: 'G-FG8DVNWH87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAraXSP-5VTrVWJdHNXg9DkLdLUjTl-OI4',
    appId: '1:448392600157:android:cad92408459c9875dccbb4',
    messagingSenderId: '448392600157',
    projectId: 'testing-cli-a28a7',
    storageBucket: 'testing-cli-a28a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfP0V_mBaFoLNOFUHf7nCSmKOQrXKDGpQ',
    appId: '1:448392600157:ios:d7e7f4919a27bafedccbb4',
    messagingSenderId: '448392600157',
    projectId: 'testing-cli-a28a7',
    storageBucket: 'testing-cli-a28a7.appspot.com',
    iosBundleId: 'com.example.techMedia',
  );
}
